avoid cmake version parsing in rust (#83)

diff --git a/tests/common/cmake_old/cmake b/tests/common/cmake_old/cmake
--- a/tests/common/cmake_old/cmake
+++ b/tests/common/cmake_old/cmake
@@ -1,4 +1,8 @@
 #!/bin/bash
 
-# Write an old version to stderr
-echo "3.12.4" 1>&2
+echo "CMake Error at cmake_version.cmake:5 (cmake_minimum_required):"
+echo "  CMake 3.19 or higher is required.  You are running version 3.12.4"
+echo ""
+echo ""
+
+exit 1
